routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
 Route::get('/', function () {
     return view('welcome');
 });
*/

Auth::routes();
Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index');

//User
Route::group(['middleware' => 'auth','prefix' => 'user'], function () {
    Route::get('/transaksi', 'TransaksiController@index');
    Route::resource('/kelas', 'KelasController');
});

//Auth Admin
Route::get('/login/admin', 'Auth\LoginController@showAdminLoginForm');
Route::get('/register/admin', 'Auth\RegisterController@showAdminRegisterForm');
Route::post('/login/admin', 'Auth\LoginController@adminLogin');
Route::post('/register/admin', 'Auth\RegisterController@createAdmin');

//Admin
Route::get('/', 'AdminController@index');
Route::get('/admin', 'AdminController@index')->name('admin.home');

Route::group(['prefix' => 'admin','middleware' => 'auth:admin'], function () {
    Route::resource('/kelas', 'KelasController');
    Route::resource('/user', 'UserController');
});
/*
Auth::routes();
Route::view('/', 'welcome');

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin'], function () {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.home');
});

Route::get('/admin', function(){
    return view('admin');
})->name('adminpage');

Route::get('admin-login','Auth\AdminLoginController@showLoginForm');
Route::post('admin-login', ['as' => 'admin-login', 'uses' => 'Auth\AdminLoginController@login']);

Route::get('admin-register','Auth\AdminLoginController@showRegisterPage');
Route::post('admin-register', 'Auth\AdminLoginController@register')->name('admin.register');
*/

app/Kelas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kelas extends Model
{
    protected $table = 'kelas';
    protected $fillable = ['kelas','wali_kelas','tahun_ajaran'];
}

app/Http/Controllers/KelasController.php
<?php
namespace App\Http\Controllers;

use App\Kelas;
use Illuminate\Http\Request;

class KelasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return
     */
    public function index()
    {
        $kelas = Kelas::get();
        return view('admin.kelas.index',compact('kelas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return
     */
    public function create()
    {
        return view('admin.kelas.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param
     * @return
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'kelas' => 'required',
            'wali_kelas' => 'required',
            'tahun_ajaran' => 'required'
        ]);

        Kelas::create($request->all());
        return redirect()->route('kelas.index');
    }

    /**
     * Display the specified resource.
     *
     * @param
     * @return
     */
    public function show(Kelas $kelas)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param
     * @return
     */
    public function edit($id)
    {
        $kelas = Kelas::findOrFail($id);
        return view('admin.kelas.edit',compact('kelas'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param
     * @param
     * @return
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'kelas' => 'required',
            'wali_kelas' => 'required',
            'tahun_ajaran' => 'required'
        ]);

        Kelas::find($id)->update($request->all());
        return redirect()->route('kelas.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param
     * @return
     */
    public function destroy($id)
    {
        Kelas::find($id)->delete();
        return redirect()->route('kelas.index');
    }
}

resources/views/admin/kelas/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div class="page-title-icon">
                    <i class="pe-7s-user icon-gradient bg-mean-fruit">
                    </i>
                </div>
                <div>Tambah Kelas
                    <div class="page-title-subheading">Menambahkan Daftar Kelas
                    </div>
                </div>
            </div>
            <div class="page-title-actions">
                <button type="button" data-toggle="tooltip" title="Bintang hehe" data-placement="bottom" class="btn-shadow mr-3 btn btn-dark">
                    <i class="fa fa-star"></i>
                </button>
            </div>
        </div>
    </div>
    <form method="POST" action="{{route('kelas.store')}}" enctype="multipart/form-data">
        {{ csrf_field() }}
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group{{ $errors->has('kelas') ? ' has-error' : '' }}">
                            <label for="kelas" class="col-md-4 control-label">Kelas</label>
                            <div class="col-md-6">
                                <input id="kelas" type="text" class="form-control" name="kelas" value="" required>
                                @if ($errors->has('kelas'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('kelas') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        {{-- <div class="form-group{{ $errors->has('nomor_anggota') ? ' has-error' : '' }}">
                                  <label for="penyedia" class="col-md-4 control-label">Penyedia</label>
                                    <div class="col-md-6">
                                        <input id="penyedia" type="text" class="form-control" name="penyedia" value="{{ old('penyedia') }}" required>
                                        @if ($errors->has('penyedia'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('penyedia') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div> --}}



                        <div class="form-group{{ $errors->has('wali_kelas') ? ' has-error' : '' }}">
                            <label for="wali_kelas" class="col-md-4 control-label">Wali Kelas</label>
                            <div class="col-md-12">
                                <input id="wali_kelas" type="text"  class="form-control" name="wali_kelas" value="" required>
                                @if ($errors->has('wali_kelas'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('wali_kelas') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('tahun_ajaran') ? ' has-error' : '' }}">
                            <label for="tahun_ajaran" class="col-md-4 control-label">Tahun Ajaran</label>
                            <div class="col-md-12">
                                <input id="tahun_ajaran" type="text" class="form-control" name="tahun_ajaran" value="" >
                                @if ($errors->has('tahun_ajaran'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('tahun_ajaran') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <button type="submit" class="btn btn-primary" id="submit">
                                    Submit
                                </button>
                                <button type="reset" class="btn btn-danger">
                                    Reset
                                </button>
                                <a href="{{route('kelas.index')}}" class="btn btn-light pull-right">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>

@endsection

resources/views/admin/kelas/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div class="page-title-icon">
                    <i class="pe-7s-user icon-gradient bg-mean-fruit">
                    </i>
                </div>
                <div>Edit Kelas {{$kelas->nama}}
                    <div class="page-title-subheading">Mengubah Daftar Kelas
                    </div>
                </div>
            </div>
            <div class="page-title-actions">
                <button type="button" data-toggle="tooltip" title="Bintang hehe" data-placement="bottom" class="btn-shadow mr-3 btn btn-dark">
                    <i class="fa fa-star"></i>
                </button>
            </div>
        </div>
    </div>
    <form method="POST" action="{{route('kelas.update',$kelas->id)}}" enctype="multipart/form-data">
        {{ csrf_field() }}
        {{method_field('PUT')}}
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group{{ $errors->has('kelas') ? ' has-error' : '' }}">
                            <label for="kelas" class="col-md-4 control-label">Kelas</label>
                            <div class="col-md-6">
                                <input id="kelas" type="text" class="form-control" name="kelas" value="{{$kelas->kelas}}" required>
                                @if ($errors->has('kelas'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('kelas') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        {{-- <div class="form-group{{ $errors->has('nomor_anggota') ? ' has-error' : '' }}">
                                  <label for="penyedia" class="col-md-4 control-label">Penyedia</label>
                                    <div class="col-md-6">
                                        <input id="penyedia" type="text" class="form-control" name="penyedia" value="{{ old('penyedia') }}" required>
                                        @if ($errors->has('penyedia'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('penyedia') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div> --}}



                        <div class="form-group{{ $errors->has('wali_kelas') ? ' has-error' : '' }}">
                            <label for="wali_kelas" class="col-md-4 control-label">Wali Kelas</label>
                            <div class="col-md-12">
                                <input id="wali_kelas" type="text"  class="form-control" name="wali_kelas" value="{{$kelas->wali_kelas}}" required>
                                @if ($errors->has('wali_kelas'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('wali_kelas') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('tahun_ajaran') ? ' has-error' : '' }}">
                            <label for="tahun_ajaran" class="col-md-4 control-label">Tahun Ajaran</label>
                            <div class="col-md-12">
                                <input id="tahun_ajaran" type="text" class="form-control" name="tahun_ajaran" value="{{$kelas->tahun_ajaran}}" >
                                @if ($errors->has('tahun_ajaran'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('tahun_ajaran') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <button type="submit" class="btn btn-primary" id="submit">
                                    Submit
                                </button>
                                <button type="reset" class="btn btn-danger">
                                    Reset
                                </button>
                                <a href="{{route('kelas.index')}}" class="btn btn-light pull-right">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>

@endsection

resources/views/admin/kelas/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div class="page-title-icon">
                    <i class="pe-7s-menu icon-gradient bg-mean-fruit">
                    </i>
                </div>
                <div>Kelas
                    <div class="page-title-subheading">Daftar Kelas Siswa
                    </div>
                </div>
{{--                <!-- Button trigger modal -->--}}
{{--                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">--}}
{{--                    Launch demo modal--}}
{{--                </button>--}}

{{--                <!-- Modal -->--}}
{{--                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">--}}
{{--                    <div class="modal-dialog" role="document">--}}
{{--                        <div class="modal-content">--}}
{{--                            <div class="modal-header">--}}
{{--                                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>--}}
{{--                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">--}}
{{--                                    <span aria-hidden="true">&times;</span>--}}
{{--                                </button>--}}
{{--                            </div>--}}
{{--                            <div class="modal-body">--}}
{{--                                ...--}}
{{--                            </div>--}}
{{--                            <div class="modal-footer">--}}
{{--                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>--}}
{{--                                <button type="button" class="btn btn-primary">Save changes</button>--}}
{{--                            </div>--}}
{{--                        </div>--}}
{{--                    </div>--}}
{{--                </div>--}}
            </div>

            <div class="page-title-actions">
                <button type="button" data-toggle="tooltip" title="Bintang hehe" data-placement="bottom" class="btn-shadow mr-3 btn btn-dark">
                    <i class="fa fa-star"></i>
                </button>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="main-card mb-3 card">
                <div class="card-header">Tabel Kelas
                    <div class="btn-actions-pane-right">
                        <div role="group" class="btn-group-sm btn-group">
                            <a href="{{route('kelas.create')}}" class="btn btn-focus" >Tambah +</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="align-middle mb-0 table table-borderless table-striped table-hover" id="dataTable">
                            <thead>
                            <tr>
                                <th class="text-center">No</th>
                                <th class="text-center">Kelas</th>
                                <th class="text-center">Wali Kelas</th>
                                <th class="text-center">Tahun Ajaran</th>
                                <th class="text-center">Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            @php
                                $i=1
                            @endphp
                            @foreach($kelas as $k)
                                <tr>
                                    <td class="text-center text-muted">{{$i++}}</td>
                                    <td class="text-center">{{$k->kelas}}</td>
                                    <td class="text-center">{{$k->wali_kelas}}</td>
                                    <td class="text-center">{{$k->tahun_ajaran}}</td>
                                    <td class="text-center">
                                        <div class="columns">
                                            <a href="{{route('kelas.edit',$k->id)}}" class="mr-2 btn-wide btn btn-info">Edit</a>
                                            <a href="" class="mr-2 btn-icon btn-icon-only btn btn-danger" data-toggle="modal" data-target="#modelId" onclick="prepare({{$k->id}})"><i class="pe-7s-trash btn-icon-wrapper"> </i></a>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="d-block text-center card-footer">
{{--                    <button class="mr-2 btn-icon btn-icon-only btn btn-outline-danger"><i class="pe-7s-trash btn-icon-wrapper"> </i></button>--}}
                    <button class="btn-wide btn btn-success">Oke</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modelId" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
        <div class="modal-dialog" role="document" style="margin-top: 15vh">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Konfirmasi Hapus Kelas</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{route('kelas.destroy', $k->id)}}" method="post">
                    {{ csrf_field() }}
                    {{ method_field('delete') }}
                    <input type="hidden" name="id" id="kelasid" readonly>
                    <div class="modal-body">
                        Apakah anda yakin ingin menghapus kelas <b><span id="kelas">{{$k->kelas}}</span></b>?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Tidak</button>
                        <input type="submit" value="Hapus" class="btn btn-danger">
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection