routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
 Route::get('/', function () {
     return view('welcome');
 });
*/

Auth::routes();
Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index');

//User
Route::group(['middleware' => 'auth','prefix' => 'user'], function () {
    Route::get('/transaksi', 'TransaksiController@index');
    Route::resource('/kelas', 'KelasController');
});

//Auth Admin
Route::get('/login/admin', 'Auth\LoginController@showAdminLoginForm');
Route::get('/register/admin', 'Auth\RegisterController@showAdminRegisterForm');
Route::post('/login/admin', 'Auth\LoginController@adminLogin');
Route::post('/register/admin', 'Auth\RegisterController@createAdmin');

//Admin
Route::get('/', 'AdminController@index');
Route::get('/admin', 'AdminController@index')->name('admin.home');

Route::group(['prefix' => 'admin','middleware' => 'auth:admin'], function () {
    Route::resource('/kelas', 'KelasController');
    Route::resource('/user', 'UserController');
});
/*
Auth::routes();
Route::view('/', 'welcome');

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin'], function () {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.home');
});

Route::get('/admin', function(){
    return view('admin');
})->name('adminpage');

Route::get('admin-login','Auth\AdminLoginController@showLoginForm');
Route::post('admin-login', ['as' => 'admin-login', 'uses' => 'Auth\AdminLoginController@login']);

Route::get('admin-register','Auth\AdminLoginController@showRegisterPage');
Route::post('admin-register', 'Auth\AdminLoginController@register')->name('admin.register');
*/

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected $guard = 'user';

    protected $table = 'user';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username','name', 'email', 'password','tahun_masuk', 'id_level','id_kelas'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function level(){
        return $this->hasOne('App\Level','id','id_level');
    }

    public function kelas(){
        return $this->hasOne('App\Kelas','id','id_kelas');
    }

    public function spp(){
        return $this->hasOne('App\Spp','id','id_spp');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Spp;
use App\User;
use App\Kelas;
use App\Level;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return
     */
    public function index()
    {
        $user = User::with('kelas','level')->get();
        return view('admin.user.index',compact('user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return
     */
    public function create()
    {
        $level = Level::all();
        $kelas = Kelas::all();
        $spp = Spp::all();
        return view('admin.user.create',compact('level','kelas','spp'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param
     * @return
     */
    public function store(Request $request)
    {
//        $count = User::where('username',$request->input('username'))->count();
//
//        if ($count>0){
//            return redirect()->route('user.create');
//        }

        $this->validate($request, [
            'username' => 'required',
            'name' => 'required',
            'email' => 'required',
            'password' => 'required',
            'tahun_masuk' => 'required',
        ]);

        User::create([
            'username' => $request->input('username'),
            'name' => $request->input('name'),
            'email' => $request->input('email'),
            'password' => bcrypt($request->input('password')),
            'tahun_masuk' => $request->input('tahun_masuk'),
            'id_level' => $request->input('level'),
            'id_kelas' => $request->input('kelas'),
            'id_spp' => $request->input('spp')
        ]);

        return redirect()->route('user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param
     * @return
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param
     * @return
     */
    public function edit($id)
    {
        $level = Level::all();
        $kelas = Kelas::all();
        $spp = Spp::all();
        $user = User::findOrFail($id);
        return view('admin.user.edit',compact('level','kelas','user','spp'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param
     * @param
     * @return
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'username' => 'required',
            'name' => 'required',
            'email' => 'required',
            'password' => 'required',
            'tahun_masuk' => 'required',
        ]);

        User::find($id)->update($request->all());
        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param
     * @return
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div class="page-title-icon">
                    <i class="pe-7s-user icon-gradient bg-mean-fruit">
                    </i>
                </div>
                <div>Tambah User
                    <div class="page-title-subheading">Menambahkan User
                    </div>
                </div>
            </div>
            <div class="page-title-actions">
                <button type="button" data-toggle="tooltip" title="Bintang hehe" data-placement="bottom" class="btn-shadow mr-3 btn btn-dark">
                    <i class="fa fa-star"></i>
                </button>
            </div>
        </div>
    </div>
    <form method="POST" action="{{route('user.store')}}" enctype="multipart/form-data">
        {{ csrf_field() }}
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group{{ $errors->has('username') ? ' has-error' : '' }}">
                            <label for="username" class="col-md-4 control-label">Username</label>
                            <div class="col-md-8">
                                <input id="username" type="text" class="form-control" name="username" value="" required>
                                @if ($errors->has('username'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('username') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Nama</label>
                            <div class="col-md-12">
                                <input id="name" type="text"  class="form-control" name="name" value="" required>
                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">Email</label>
                            <div class="col-md-12">
                                <input id="email" type="email" class="form-control" name="email" value="" >
                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Password</label>
                            <div class="col-md-12">
                                <input id="password" type="password"  class="form-control" name="password" value="" required>
                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('tahun_masuk') ? ' has-error' : '' }}">
                            <label for="tahun_masuk" class="col-md-4 control-label">Tahun Masuk</label>
                            <div class="col-md-8">
                                <input id="tahun_masuk" type="text"  class="form-control" name="tahun_masuk" value="" required>
                                @if ($errors->has('tahun_masuk'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('tahun_masuk') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('level') ? ' has-error' : '' }}">
                            <label for="level" class="col-md-4 control-label">Level</label>
                            <div class="col-md-8">
                                <select name="level" id="" class="form-control">
                                    <option value="">--Pilih Level--</option>
                                    @foreach($level as $l)
                                        <option value="{{$l->id}}">{{$l->nama}}</option>
                                    @endforeach
                                </select>
                                @if ($errors->has('level'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('level') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('kelas') ? ' has-error' : '' }}">
                            <label for="kelas" class="col-md-4 control-label">Kelas</label>
                            <div class="col-md-8">
                                <select name="kelas" id="" class="form-control">
                                    <option value="">--Pilih Kelas--</option>
                                    @foreach($kelas as $k)
                                        <option value="{{$k->id}}">{{$k->kelas}}</option>
                                    @endforeach
                                </select>
                                @if ($errors->has('kelas'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('kelas') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('spp') ? ' has-error' : '' }}">
                            <label for="spp" class="col-md-4 control-label">Spp</label>
                            <div class="col-md-8">
                                <select name="spp" id="" class="form-control">
                                    <option value="">--Pilih Spp--</option>
                                    @foreach($spp as $s)
                                        <option value="{{$s->id}}">{{$s->nama}}</option>
                                    @endforeach
                                </select>
                                @if ($errors->has('spp'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('spp') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <button type="submit" class="btn btn-primary" id="submit">
                                    Submit
                                </button>
                                <button type="reset" class="btn btn-danger">
                                    Reset
                                </button>
                                <a href="{{route('user.index')}}" class="btn btn-light pull-right">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>

@endsection

resources/views/admin/user/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div class="page-title-icon">
                    <i class="pe-7s-user icon-gradient bg-mean-fruit">
                    </i>
                </div>
                <div>Edit User <b>{{$user->name}}</b>
                    <div class="page-title-subheading">Mengedit User
                    </div>
                </div>
            </div>
            <div class="page-title-actions">
                <button type="button" data-toggle="tooltip" title="Bintang hehe" data-placement="bottom" class="btn-shadow mr-3 btn btn-dark">
                    <i class="fa fa-star"></i>
                </button>
            </div>
        </div>
    </div>
    <form method="POST" action="{{route('user.update',$user->id)}}" enctype="multipart/form-data">
        {{ csrf_field() }}
        {{ method_field('put')}}
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group{{ $errors->has('username') ? ' has-error' : '' }}">
                            <label for="username" class="col-md-4 control-label">Username</label>
                            <div class="col-md-8">
                                <input id="username" type="text" class="form-control" name="username" value="{{$user->username}}" required>
                                @if ($errors->has('username'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('username') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Nama</label>
                            <div class="col-md-12">
                                <input id="name" type="text"  class="form-control" name="name" value="{{$user->name}}" required>
                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">Email</label>
                            <div class="col-md-12">
                                <input id="email" type="email" class="form-control" name="email" value="{{$user->email}}" >
                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Password</label>
                            <div class="col-md-12">
                                <input id="password" type="password"  class="form-control" name="password" value="{{$user->password}}" readonly>
                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('tahun_masuk') ? ' has-error' : '' }}">
                            <label for="tahun_masuk" class="col-md-4 control-label">Tahun Masuk</label>
                            <div class="col-md-8">
                                <input id="tahun_masuk" type="text"  class="form-control" name="tahun_masuk" value="{{$user->tahun_masuk}}" required>
                                @if ($errors->has('tahun_masuk'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('tahun_masuk') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('level') ? ' has-error' : '' }}">
                            <label for="level" class="col-md-4 control-label">Level</label>
                            <div class="col-md-8">
                                <select name="level" id="" class="form-control">
                                    <option value="{{$user->id_level}}">{{$user->level->nama}}</option>
                                    @foreach($level as $l)
                                            @if ($l->id != $user->id_level)
                                                <option value="{{$l->id}}">{{$l->nama}}</option>
                                            @endif
                                    @endforeach
                                </select>
                                @if ($errors->has('level'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('level') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('kelas') ? ' has-error' : '' }}">
                            <label for="kelas" class="col-md-4 control-label">Kelas</label>
                            <div class="col-md-8">
                                <select name="kelas" id="" class="form-control">
                                    <option value="{{$user->id_kelas}}">{{$user->kelas->kelas}}</option>
                                    @foreach($kelas as $k)
                                        @if ($k->id != $user->id_kelas)
                                            <option value="{{$k->id}}">{{$k->kelas}}</option>
                                        @endif
                                    @endforeach
                                </select>
                                @if ($errors->has('kelas'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('kelas') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('spp') ? ' has-error' : '' }}">
                            <label for="spp" class="col-md-4 control-label">Spp</label>
                            <div class="col-md-8">
                                <select name="spp" id="" class="form-control">
                                    <option value="{{$user->id_spp}}">{{$user->spp->nama}}</option>
                                    @foreach($spp as $s)
                                        @if ($s->id != $user->id_spp)
                                            <option value="{{$s->id}}">{{$s->nama}}</option>
                                        @endif
                                    @endforeach
                                </select>
                                @if ($errors->has('spp'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('spp') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <button type="submit" class="btn btn-primary" id="submit">
                                    Submit
                                </button>
                                <button type="reset" class="btn btn-danger">
                                    Reset
                                </button>
                                <a href="{{route('user.index')}}" class="btn btn-light pull-right">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>

@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div class="page-title-icon">
                    <i class="pe-7s-user icon-gradient bg-mean-fruit">
                    </i>
                </div>
                <div>User
                    <div class="page-title-subheading">Daftar Pengguna
                    </div>
                </div>
            </div>

            <div class="page-title-actions">
                <button type="button" data-toggle="tooltip" title="Bintang hehe" data-placement="bottom" class="btn-shadow mr-3 btn btn-dark">
                    <i class="fa fa-star"></i>
                </button>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="main-card mb-3 card">
                <div class="card-header">Tabel User
                    <div class="btn-actions-pane-right">
                        <div role="group" class="btn-group-sm btn-group">
                            <a href="{{route('user.create')}}" class="btn btn-focus" >Tambah +</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="align-middle mb-0 table table-borderless table-striped table-hover" id="dataTable">
                            <thead>
                            <tr>
                                <th class="text-center">No</th>
                                <th class="text-center">Nama</th>
                                <th class="text-center">Email</th>
                                <th class="text-center">Tahun Masuk</th>
                                <th class="text-center">Level</th>
                                <th class="text-center">Kelas</th>
                                <th class="text-center">Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            @php
                                $i=1
                            @endphp
                            @foreach($user as $u)
                                <tr>
                                    <td class="text-center text-muted">{{$i++}}</td>
                                    <td class="text-center">{{$u->name}}</td>
                                    <td class="text-center">{{$u->email}}</td>
                                    <td class="text-center">{{$u->tahun_masuk}}</td>
                                    <td class="text-center">{{$u->level->nama}}</td>
                                    <td class="text-center">{{$u->kelas->kelas}}</td>
                                    <td class="text-center">
                                        <div class="columns">
                                            <a href="{{route('user.edit', $u->id)}}" class="mr-2 btn-wide btn btn-info">Edit</a>
                                            <a href="" class="mr-2 btn-icon btn-icon-only btn btn-danger" data-toggle="modal" data-target="#modelId" onclick="prepare({{$u->id}})"><i class="pe-7s-trash btn-icon-wrapper"> </i></a>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="d-block text-center card-footer">
{{--                    <button class="mr-2 btn-icon btn-icon-only btn btn-outline-danger"><i class="pe-7s-trash btn-icon-wrapper"> </i></button>--}}
                    <button class="btn-wide btn btn-success">Oke</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modelId" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
        <div class="modal-dialog" role="document" style="margin-top: 15vh">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Konfirmasi Hapus User</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="" method="post">
                    {{ csrf_field() }}
                    {{ method_field('delete') }}
                    <input type="hidden" name="id" id="userid" readonly>
                    <div class="modal-body">
                        Apakah anda yakin ingin menghapus User <b><span id="kelas">{{$u->name}}</span></b>?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Tidak</button>
                        <input type="submit" value="Hapus" class="btn btn-danger">
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection